### ISSUE TITLE
Can't find push configuration values in new Azure portal

### ISSUE THREAD

**Issue by pmullins-ewn** [MicrosoftDocs/appcenter-docs#695]
Hi there, I'm attempting to set up push notifications in my UWP app. Under boldfaced item #2 (https://docs.microsoft.com/en-us/appcenter/sdk/push/uwp#2-get-the-package-sid-and-application-secret-from-the-partner-center). I was able to access my application's package SID listed in sub-step 2. However, on sub-step 3, where we navigate to the Microsoft Application Registration portal, when I clicked on the "Live Services" link, I was taken to the portal, where I was notified that my application could not be found or no longer exists. 

From there, as prompted, I navigated to the new Azure portal, and created a new Application registration. However, I was unable to find the package SID or app secret for the new Application. The closest thing I could find resembling the app secret was creating a new Client Secret under "Certificates & Secrets".

Where should I go to find a package SID for this app registration, and is the Client Secret value I used what I should pass to App Center as the App Secret?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb42032-a67b-b601-7ef0-bdf1c8838f73
* Version Independent ID: 4d052b88-6fe1-358e-47a7-4d2687f02c10
* Content: [App Center Push for Universal Windows Platform - Visual Studio App Center](https://docs.microsoft.com/en-us/appcenter/sdk/push/uwp#2-get-the-package-sid-and-application-secret-from-the-partner-center)
* Content Source: [docs/sdk/push/uwp.md](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/sdk/push/uwp.md)
* Service: **vs-appcenter**
* GitHub Login: @elamalani
* Microsoft Alias: **emalani**

**Comment by jwargo** [comment]
@pmullins-ewn we updated the docs last week on this. The new portal uses different values, I was able to use the App ID rather than the SSID and it worked for me.

**Comment by pmullins-ewn** [comment]
@jwargo What value were you using as the Security Key? That's the value I'm unable to access in the manner that the docs outline. I'm attempting to use the Client Secret value from the Azure portal, but I'm getting an error in App Center saying "Failed to apply settings: push configuration is invalid."

Additionally, how does the app registration on the Azure portal correspond to my local app? Associating my app with the app store as outlined in the docs does not create an app registration in the app portal, so I don't quite understand how these two parts link together.

**Comment by jwargo** [comment]
@pmullins-ewn Have you looked at the updated documentation? The SDK team just updated it last week with updated screen shots and more information. 

When I tested this, I grabbed the Application ID (not the SSID) and the secret that was on the same page. I can't seem to find the details anymore as my app isn't showing up in the portal. I don't do any Windows development, so I was just poking around and got it to work. 

We believe the docs are accurate as of last week; if you can't get this to work, then please contact our dedicated support team, they can help you through this and get the docs updated yet again if more information is needed. Just click the blue chat button on the bottom-right corner of any App Center page.

**Comment by pmullins-ewn** [comment]
@jwargo thanks for the direction. It looks like after doing a fresh refresh of the page I initially cited, I'm unfortunately still seeing documentation using the old platform for UWP apps. I've navigated to the docs via the question mark next to the profile link on App Center, and then tried navigating to `Push/App Configuration/UWP`, as well as `SDK/Push/UWP`, and I'm still seeing references to the App Secret on the old platform and no references to the Azure platform.

I'll go ahead and contact the support team for additional assistance.
